// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/khalid/KhalidSystemsConsole.tsx": () => import("../components/mockups/khalid/KhalidSystemsConsole.tsx"),
  "./components/mockups/templates/NeonHorizonsTravelCarousel-Ow76Ra/App.tsx": () => import("../components/mockups/templates/NeonHorizonsTravelCarousel-Ow76Ra/App.tsx"),
  "./components/mockups/templates/NeonHorizonsTravelCarousel-yjWGSv/App.tsx": () => import("../components/mockups/templates/NeonHorizonsTravelCarousel-yjWGSv/App.tsx")
};
